### ISSUE TITLE
Cant Login

### ISSUE THREAD

**Issue by billyriantono** [aidanmacgregor/Netflix_ATV_L3_DRM_Uncertified_Mod#1]
Hi @aidanmacgregor,
Thank you for the awesome works , i have try it, but after NF Loading Logo,
It's show that i can't connect to NF Server screen ( screenshot attached ) 

Would you mind to advise in this issue, please ? 

Thank you
![photo_2023-01-30_13-50-26](https://user-images.githubusercontent.com/3274396/215425392-05773b0f-679c-4b44-ba69-80d064f19153.jpg)

**Comment by aidanmacgregor** [comment]
Now have a pre compiled apk available :)
