### ISSUE TITLE
HD not working, playback in 480p only

### ISSUE THREAD

**Issue by divyanshluthra** [aidanmacgregor/Netflix_ATV_L3_DRM_Uncertified_Mod#11]
![16921854133172272905883141371463](https://github.com/aidanmacgregor/Netflix_ATV_L3_DRM_Uncertified_Mod/assets/96992259/2f80e98e-93c8-4a32-9d27-6c77b07ed3bb)

**Comment by divyanshluthra** [comment]
Even though device supports widevine L1

**Comment by danyev3** [comment]
Same issue here on Nebula Capsule 3 Projector, basically unwatchable

**Comment by aidanmacgregor** [comment]
Sorry, only SD works, there was a solution for L1, this required you to use a modified apk (4.x) to get an ESN then modifying the apk for your device, this had to be done for every device as apks wouldn't work universally, unfortunately Netflix blocked this method about a year ago (They also blocked this SD mod but worked around that :)

**Comment by aidanmacgregor** [comment]
No HD Solution currently

**Comment by aidanmacgregor** [comment]
No HD Solution currently

**Comment by nathanbirrell** [comment]
Do we know if there will ever be a HD solution? 

By the sounds of it it's something only Netflix can address by easing this restriction 😞
