### ISSUE TITLE
¿You can make one with Netflix For Android TV Widevine L1 + 1080p?

### ISSUE THREAD

**Issue by Braiancamejo** [aidanmacgregor/Netflix_ATV_L3_DRM_Uncertified_Mod#15]
Please since it is difficult to use in Widevine L3 854x480 and it is complicated in that quality, a much better mod could do it in HD quality. 

I am looking forward to your response.

**Comment by aidanmacgregor** [comment]
The most recent L1 HD TV Netflix solution was unfortunately complicated as required every device to have a customised apk to its specific widevine key, as far as i know that stopped working around a year or more ago around the time my older L3 mod stopped working :)
