### ISSUE TITLE
Video playback is lagging after a while (Raspberry 4, KonstaKANG Android TV 11)

### ISSUE THREAD

**Issue by BenjaminStonawski** [aidanmacgregor/Netflix_ATV_L3_DRM_Uncertified_Mod#16]
Hello there!
I tried this app and it seems working, but after 1-2 minutes of video playback, the video starts to lag and won't load. If I try to fast-forward the video, it'll start loading and stick at "99%" so basically, I can't watch anything.
What is causing the issue?

**Comment by aidanmacgregor** [comment]
Sounds like a firmware issue decoding the video stream, dont think much i could do from my side to improve the performance here :)
