### ISSUE TITLE
Impossible to install the new apk, after recompiling the source files

### ISSUE THREAD

**Issue by MarGraz** [aidanmacgregor/Netflix_ATV_L3_DRM_Uncertified_Mod#2]
Hi,

thank you @aidanmacgregor for your work.
I'm trying to follow your readme to install the "Netflix_ATV_L3_DRM_Uncertified_Mod" apk on my S905X tv box (whit your Aidan's ROM v9 [AMPI.3933.M4GC]). 

In your source file I successfully modified the `smali\com\netflix\mediaclient\service\configuration\esn\BaseEsnProvider.smali` file (using Visual Studio Code), at line 1885 adding my system id. On Windows 11 I installed the latest version of "Java JRE", "apktool.jar" and "apktool.bat", and the recompiling works, I have used the command: `java -jar C:\Windows\apktool.jar b .\com.netflix.ninja-2.0_build_295-295-minAPI23\ com.netflix.ninja-2.0_build_295-295-minAPI23.apk`, but **when I try to install the new apk in my TV box, it returns the error: "App not installed"**.

**Probably I'm doing something wrong**, I don't know if I need to modify something in the manifest file, or if I need to add a signature to the apk. Could you help me?

Thank you

**Comment by MarGraz** [comment]
@aidanmacgregor **I was able to install the recompiled apk**, the problem was that my apk was not self-signed. To do it, I used an app on my Android phone, called [apk-signer](https://play.google.com/store/apps/details?id=com.haibison.apksigner&hl=en_US) that did all the job, and returned a signed apk ([here a video on how to use apk-signer, starting from 4 min 37 seconds](https://youtu.be/bisMnhLrIt4?t=277)).

**Unfortunately, Netflix wont work, it return error ui-113** :(

**Comment by MarGraz** [comment]
@aidanmacgregor I think that could be useful to add this information to the readme.

**Comment by aidanmacgregor** [comment]
Now have a pre compiled version availible :)

**Comment by MarGraz** [comment]
> Now have a pre compiled version availible :)

Thank you @aidanmacgregor, I saw that you have updated the readme with the download link. **I tried it, it works!** 🥳

Thank you
