### ISSUE TITLE
Error UI-113 running the re-compiled apk

### ISSUE THREAD

**Issue by MarGraz** [aidanmacgregor/Netflix_ATV_L3_DRM_Uncertified_Mod#3]
The esn included in the apk seems not working anymore. I added my "system id", but when I open the Netflix app it returns error ui-113.

In [this issue](https://github.com/aidanmacgregor/Netflix_ATV_L3_DRM_Uncertified_Mod/issues/2) that I closed, the compiling procedure that I followed.

**Comment by aidanmacgregor** [comment]
Now have a pre compiled apk available :)
