### ISSUE TITLE
No audio issue

### ISSUE THREAD

**Issue by KneesDev** [aidanmacgregor/Netflix_ATV_L3_DRM_Uncertified_Mod#7]
There is often no audio on whatever I watch using the app. When that happens, it sometimes get solved for the current episode I'm watching by moving the playback to a later time.

**Comment by aidanmacgregor** [comment]
oh, really strange, not seen anyone else with this issue, would suggest its maybe a firmware/codec issue, do you have another device to test on? even a phone with keyboard/remote (devices below android 12 should work with the current apk)

**Comment by KneesDev** [comment]
My phone is Android 13, so I don't have any devices below 12 except my Android TV.
Something I've noticed is that if I open YouTube, play a video, quickly press the home button while the video is playing and play the Netflix episode, the audio works just fine (and sometimes even on the next episode). It is strange so yeah, it could be a firmware or codec issue. I've never seen anyone else with this issue with any Android apps in general so I'm probably the only one experiencing this.

I'm not sure if I can do anything about it. Also, can you tell me how to play the Test Patterns "series" on the TV app? I know how to do it on a browser but it's hidden from search (at least on the Netflix for Android TV).

**Comment by aidanmacgregor** [comment]
i have it in my watch list i think :)
